from config import db

class Employee(db.Model):
    __tablename__ = "employee"

    employee_id = db.Column(db.Text, primary_key=True)
    nom = db.Column(db.Text)
    prenom = db.Column(db.Text)
    sexe = db.Column(db.Text)
    date_naissance = db.Column(db.Text)
    age = db.Column(db.Integer)
    etat_civil = db.Column(db.Text)
    nombre_enfants = db.Column(db.Integer)
    niveau_etude = db.Column(db.Text)
    poste = db.Column(db.Text)
    departement = db.Column(db.Text)
    type_contrat = db.Column(db.Text)
    anciennete_annees = db.Column(db.Integer)
    salaire_mensuel = db.Column(db.Integer)
    prime_rendement = db.Column(db.Integer)
    heures_travail_semaine = db.Column(db.Integer)
    heures_absence_mois = db.Column(db.Integer)
    retards_mois = db.Column(db.Integer)
    jours_conge_restant = db.Column(db.Integer)
    statut_presence = db.Column(db.Text)
    rfid_uid = db.Column(db.Text)
    shift_travail = db.Column(db.Text)
    performance_moyenne = db.Column(db.Float)
    taux_rendement = db.Column(db.Float)
    accidents_travail = db.Column(db.Integer)
    maladies_professionnelles = db.Column(db.Integer)
    evaluation_manager = db.Column(db.Integer)
    risque_absenteisme = db.Column(db.Text)
    risque_depart = db.Column(db.Text)
    date_embauche = db.Column(db.Text)